export const likelihoods = [
  {
    text: "Very Unlikely",
    value: 1,
    description: "Occurs every 25 years or more",
  },
  { text: "Unlikely", value: 2, description: "Occurs every 6-25 years" },
  { text: "Possible", value: 3, description: "Occurs every 2-5 years" },
  { text: "Likely", value: 4, description: "Occurs every year" },
  {
    text: "Very Likely",
    value: 5,
    description: "Occurs multiple times a year",
  },
];

export const impacts = [
  {
    text: "Negligible",
    value: 1,
    details: {
      ops: "No disruption, no cost impact.",
      rep: "None.",
      legal: "None.",
      people: "None.",
    },
  },
  {
    text: "Minor",
    value: 2,
    details: {
      ops: "Minor disruption and cost impact.",
      rep: "Contained within a college or unit but know to the organization.",
      legal: "Unlikely to result in litigation or claims or fines.",
      people: "Minor injury to individual.",
    },
  },
  {
    text: "Moderate",
    value: 3,
    details: {
      ops: "Moderate disruption and cost impact.",
      rep: "Local public or press interest.",
      legal: "Possible litigation, claims or fines.",
      people: "Minor injury to more than 1 person.",
    },
  },
  {
    text: "Significant",
    value: 4,
    details: {
      ops: "Significant disruption and cost impact.",
      rep: "National public or press interest.",
      legal: "Single litigation,claim or fine.",
      people: "Serious injury to one or more people.",
    },
  },
  {
    text: "Severe",
    value: 5,
    details: {
      ops: "Organization can not function and cost impact is very high.",
      rep: "National negative publicity, resignations.",
      legal: "Multiple civil & criminal lawsuits, claims and fines.",
      people: "Fatality.",
    },
  },
];

export const riskCategories = [
  "Enrollment",
  "Information Security",
  "Facilities and Deferred Maintenance",
  "Financial Sustainability",
  "Student Health and Mental Health Support",
  "Artificial Intelligence",
  "International Activities",
  "Research Compliance",
  "NCAA Regulations",
  "Labor Relations",
  "Attract, Recruit, Retain Faculty and Staff",
  "Campus Safety and Security",
  "IT Disaster Recovery",
  "Continuity Planning",
  "Information Privacy",
  "Compliance with Laws and Regulations",
  "Sexual Assault Policies and Response Procedures",
  "All Hazards Planning and Response Capabilities",
  "Auxiliary Operations",
  "Construction Projects",
  "Athletics",
  "Student Alcohol and Substance Abuse",
  "Fraud, Waste, Abuse",
  "Crisis Communications Coordination",
  "Uninsured Loss",
  "Multi-state Payroll Taxation",
  "Multi-state Business Taxation",
  "Employment Laws and Regulations",
  "Policies/Procedures Regarding Minors on Campus",
  "Academic Quality and Standards",
  "Oversight of Student Organizations",
  "Other",
];

export const statuses = [
  "Under Consideration",
  "In Progress",
  "In Place",
  "Resources Needed",
];

export const qualitativeMatrix = {
  1: { 1: "Low", 2: "Low", 3: "Low Med", 4: "Medium", 5: "Medium" },
  2: { 1: "Low", 2: "Low Med", 3: "Low Med", 4: "Medium", 5: "Med Hi" },
  3: { 1: "Low", 2: "Low Med", 3: "Medium", 4: "Med Hi", 5: "Med Hi" },
  4: { 1: "Low", 2: "Low Med", 3: "Medium", 4: "Med Hi", 5: "High" },
  5: { 1: "Low Med", 2: "Medium", 3: "Med Hi", 4: "High", 5: "High" },
};

export const leadershipResponseMap = {
  Low: "Tolerable",
  "Low Med": "Tolerable",
  Medium: "More Treatment Needed",
  "Med Hi": "Treatment Required",
  High: "Urgent Action Required",
};

export const ratingColors = {
  Low: "bg-green-100 text-green-800 border border-green-200",
  "Low Med": "bg-yellow-100 text-yellow-800 border border-yellow-200",
  Medium: "bg-orange-100 text-orange-800 border border-orange-200",
  "Med Hi": "bg-red-100 text-red-800 border border-red-200",
  High: "bg-red-200 text-red-900 border border-red-300",
};

export const aiKeywordMapping = {
  "Information Security": [
    "security",
    "cybersecurity",
    "phishing",
    "malware",
    "breach",
    "data",
    "privacy",
    "access",
    "vulnerability",
    "encryption",
  ],
  "Facilities and Deferred Maintenance": [
    "facilities",
    "maintenance",
    "hvac",
    "building",
    "infrastructure",
    "roof",
    "boiler",
    "repair",
    "construction",
  ],
  "Financial Sustainability": [
    "financial",
    "budget",
    "funding",
    "revenue",
    "tuition",
    "sustainability",
    "cost",
    "economic",
  ],
  "Student Health and Mental Health Support": [
    "student health",
    "mental health",
    "well-being",
    "counseling",
    "support",
    "wellness",
  ],
  Enrollment: [
    "enrollment",
    "admissions",
    "retention",
    "recruitment",
    "student body",
  ],
  "Compliance with Laws and Regulations": [
    "compliance",
    "regulation",
    "law",
    "legal",
    "policy",
    "audit",
  ],
  "Campus Safety and Security": [
    "safety",
    "security",
    "emergency",
    "crime",
    "police",
    "hazards",
  ],
};

export const severityKeywordMapping = {
  5: ["severe", "catastrophic", "fatality", "disabling"],
  4: ["significant", "serious", "major", "national"],
  3: ["moderate", "disruption", "local", "possible litigation"],
};

export const demoRisks = [
  {
    id: "risk_demo_1",
    riskIdNo: "CYBER-001",
    collegeUnit: "University Wide",
    department: "ITS",
    owner: "CISO",
    risk: "Cybersecurity Breach of Student Data",
    riskAnalysis:
      "Unauthorized access to student PII from phishing or malware.",
    currentControls: "MFA, annual training, firewalls, EDR software.",
    likelihood: "3",
    impact: "4",
    updatedLikelihood: "2",
    updatedImpact: "3",
    status: "In Progress",
    statusPoc: "J. Smith, IT Security",
    riskCategory: "Information Security",
  },
  {
    id: "risk_demo_2",
    riskIdNo: "FAC-003",
    collegeUnit: "C.O.S.A.M.",
    department: "Facilities",
    owner: "Director of Facilities",
    risk: "Critical HVAC Failure in Baker Science",
    riskAnalysis: "HVAC failure would halt research and cancel classes.",
    currentControls: "Bi-annual preventative maintenance, BMS monitoring.",
    likelihood: "4",
    impact: "4",
    updatedLikelihood: "1",
    updatedImpact: "3",
    status: "Resources Needed",
    statusPoc: "A. Gonzalez, Facilities",
    riskCategory: "Facilities and Deferred Maintenance",
  },
  {
    id: "risk_demo_3",
    riskIdNo: "ACAD-005",
    collegeUnit: "Office of the Provost",
    department: "CTLT",
    owner: "VP Acad. Affairs",
    risk: "Misuse of AI Compromising Academic Integrity",
    riskAnalysis: "Students using AI for assignments devalues degrees.",
    currentControls: "Honor Code, limited Turnitin AI detection.",
    likelihood: "4",
    impact: "3",
    updatedLikelihood: "3",
    updatedImpact: "2",
    status: "Under Consideration",
    statusPoc: "AI Task Force Lead",
    riskCategory: "Artificial Intelligence",
  },
  {
    id: "risk_demo_4",
    riskIdNo: "ENV-001",
    collegeUnit: "Campus Wide",
    department: "Emergency Mgmt",
    owner: "Director, Emergency Mgmt",
    risk: "Disruption from Wildfire Smoke",
    riskAnalysis:
      "Hazardous air quality poses health risks and forces cancellations.",
    currentControls:
      "PolyAlert system, AQI monitoring, some clean air shelters.",
    likelihood: "4",
    impact: "3",
    updatedLikelihood: "4",
    updatedImpact: "2",
    status: "In Progress",
    statusPoc: "E. Davis, Operations",
    riskCategory: "Campus Safety and Security",
  },
  {
    id: "risk_demo_5",
    riskIdNo: "WEB-012",
    collegeUnit: "College of Liberal Arts",
    department: "Web Services",
    owner: "CLA Web Coordinator",
    risk: "Temporary Outage of Departmental Website",
    riskAnalysis:
      "A brief outage could prevent access to faculty pages and news.",
    currentControls: "Nightly backups, uptime monitoring.",
    likelihood: "2",
    impact: "1",
    updatedLikelihood: "1",
    updatedImpact: "1",
    status: "In Place",
    statusPoc: "Web Team",
    riskCategory: "IT Disaster Recovery",
  },
  {
    id: "risk_demo_6",
    riskIdNo: "SEC-045",
    collegeUnit: "Library Services",
    department: "Access Services",
    owner: "Head of Access Services",
    risk: "Minor Theft of Personal Items in Library",
    riskAnalysis:
      "Students leaving laptops and bags unattended leads to occasional theft.",
    currentControls: "Signage, regular staff walkthroughs.",
    likelihood: "3",
    impact: "2",
    updatedLikelihood: "2",
    updatedImpact: "2",
    status: "In Place",
    statusPoc: "Library Front Desk",
    riskCategory: "Campus Safety and Security",
  },
  {
    id: "risk_demo_7",
    riskIdNo: "FAC-011",
    collegeUnit: "University Housing",
    department: "Maintenance",
    owner: "Housing Maintenance Lead",
    risk: "Major Water Pipe Burst in a Residence Hall",
    riskAnalysis:
      "A burst pipe could displace students and cause significant water damage.",
    currentControls: "Aging infrastructure, reactive maintenance.",
    likelihood: "2",
    impact: "4",
    updatedLikelihood: "1",
    updatedImpact: "4",
    status: "Resources Needed",
    statusPoc: "Housing Maintenance",
    riskCategory: "Facilities and Deferred Maintenance",
  },
  {
    id: "risk_demo_8",
    riskIdNo: "ATH-002",
    collegeUnit: "Athletics",
    department: "Compliance",
    owner: "Athletics Director",
    risk: "NCAA Violations Leading to Sanctions",
    riskAnalysis:
      "Failure to comply with NCAA bylaws could result in fines, probation, or loss of scholarships.",
    currentControls: "Compliance officer, regular rules education sessions.",
    likelihood: "3",
    impact: "5",
    updatedLikelihood: "2",
    updatedImpact: "5",
    status: "In Progress",
    statusPoc: "Compliance Officer",
    riskCategory: "NCAA Regulations",
  },
  {
    id: "risk_demo_9",
    riskIdNo: "FIN-007",
    collegeUnit: "Administration and Finance",
    department: "Budget Office",
    owner: "CFO",
    risk: "Major Drop in State Funding Allocation",
    riskAnalysis:
      "A significant reduction in state funding would require budget cuts, hiring freezes, and tuition hikes.",
    currentControls:
      "Lobbying efforts, diverse revenue streams (grants, donations).",
    likelihood: "4",
    impact: "5",
    updatedLikelihood: "4",
    updatedImpact: "4",
    status: "Under Consideration",
    statusPoc: "CFO",
    riskCategory: "Financial Sustainability",
  },
  {
    id: "risk_demo_10",
    riskIdNo: "HR-003",
    collegeUnit: "Campus Wide",
    department: "Human Resources",
    owner: "AVP Human Resources",
    risk: "Sudden Departure of Key Personnel",
    riskAnalysis:
      "Unexpected loss of a Dean, VP, or other key leader could disrupt operations and strategic direction.",
    currentControls:
      "Succession planning in some areas, but not universally applied.",
    likelihood: "5",
    impact: "3",
    updatedLikelihood: "4",
    updatedImpact: "3",
    status: "Under Consideration",
    statusPoc: "HR Leadership",
    riskCategory: "Attract, Recruit, Retain Faculty and Staff",
  },
];
